rvm:
  - 1.9.2
  - 1.8.7

branches:
  only:
    - 4.0.0
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

gemfile:
  - ci/Gemfile.rails-3.0.rb
  - ci/Gemfile.rails-3.1.rb

script: "bundle exec rake db:reset db:up test"
